config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :vins, only: [:index]

  root to: "vins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vins_controller.rb
class VinsController < ApplicationController
  include VinsManager

  def index
    @vins = fetch_vin_information(params[:search].upcase) if params[:search]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VIN Information Center</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Favicon icon -->
    <%= favicon_link_tag 'favicon.png' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="s006">
      <%= yield %>
    </div>
  </body>
</html>

app/views/vins/index.html.erb
<%= form_tag vins_path, :method => 'get' do %>
  <fieldset>
    <legend>VIN Information Center</legend>
    <div class="inner-form">
      <div class="input-field">
        <%= button_tag(type: 'submit', class: "btn-search", name: nil) do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>
          </svg>
      <% end %>
        <%= text_field_tag :search, params[:search], placeholder: 'Type a VIN Code', id: 'search', type: 'text' %>
<!--        <p style="color: red; text-align: center">-->
<!--          Clear everything-->
<!--        </p>-->
      </div>
    </div>
    <% if @vins %>
      <div class="vin-information">
        <div class="suggestion-wrap">
          <div class="information-title">VIN INFORMATION</div>
          <div class="vin-attributes">
            Provided VIN: <span><%= @vins[:provided_vin] %></span>
            Check Digit: <span><%= @vins[:check_digit] || '-' %></span>
            Valid? <span class="valid-<%= @vins[:check_digit_valid] %>">
              <%= @vins[:check_digit_valid].to_s.titleize %>
            </span>
            <br><br>

            Message: <span><%= @vins[:message] %></span>

            <% if @vins[:error].present? %>
              <br><br>
              Errors:
              <% @vins[:error].each do |e| %>
                <span><%= e %></span>
              <% end %>
            <% end %>

            <% if @vins[:suggested_vins].present? %>
              <br><br>
              Suggested VINs:
              <% @vins[:suggested_vins].each do |suggestion| %>
                <span><%= suggestion %></span>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </fieldset>
<% end %>